FIX ReflectionConstant::getDeclaringClass() returned wrong class
Speicher210/Reflection pull request #3
Opened 2021-02-09 12:24 UTC by kabachello

ISSUE: ReflectionClass::getConstants() returned constants defined in that class and its parent classes. However, ReflectionConstant::getDocComment() only searched in the class being reflected - not in its parent classes.

CAUSE: ReflectionConstant::getDeclaringClass() simply returned the class being reflected.

SOLUTION: now using ReflectionClass::getOwnConstants() to check which one of the classes actually declared the constant. This is done in ReflectionConstant::getDeclaringClass() and not in the constructor to avoid recursion.

Also added a small fix to ReflectionConstant::getCurrentConstantKeyFromClassTokens() to return 0 if no matching constant name found. Otherwise the result was the comment for the last constant with non-empty comment in the iteration.

2021-02-09 13:23 UTC, dragosprotung requested changes
Could you also add a test for this fix ?

2021-02-09 13:23 UTC, dragosprotung commented on src/ReflectionConstant.php
> +    protected $reflectedClass;
Why the new property ? Why not use the existing property (`$declaringClass`) ?

2021-02-09 13:23 UTC, dragosprotung commented on src/ReflectionConstant.php
> +                    $constDeclarationKey = 0;
Why is this needed ?

2021-02-09 13:25 UTC, dragosprotung commented on src/ReflectionConstant.php
> +                    $constDeclarationKey = 0;
I see now in your original comment. Could you add a test for this as well ?

2021-02-09 13:35 UTC, kabachello commented on src/ReflectionConstant.php
> +    protected $reflectedClass;
it would not be a $**declaring**Class then.

2021-02-09 13:39 UTC, kabachello commented
I'm very sorry, but I don't have a working PHPUnit environment right now and can't set it up on my work-PC either. I've read your contributing guide but can't do it with a reasonable effort at the moment.

2021-02-09 15:08 UTC, kabachello commented
I asked a collegue to  help with the test. Is it OK now?

2021-02-09 20:16 UTC, dragosprotung approved these changes

2021-02-10 08:11 UTC, kabachello commented
If the changes are OK, would you kindly add a tag after merge please - so that we can use the updated version in our project?

2021-02-10 11:50 UTC, merged

2021-02-10 21:13 UTC, kabachello commented
Thanks a lot!