Updates needed to allow PHP 8.1 compatibility.
Speicher210/Reflection pull request #7
Opened 2023-05-09 13:45 UTC by javierabion

Changes needed to allow PHP 8.1 compatibillity.
Drop support for PHP versions under 7.2

2023-05-09 13:48 UTC, javierabion commented
Dragos: when you merge, please update version nuembre from 1.1.0 to 1.1.1. Thanks!

2023-05-11 07:21 UTC, dragosprotung requested changes

2023-05-11 07:21 UTC, dragosprotung commented on .github/workflows/build.yml
> +          - 8.1
Please add 8.2 as well

2023-05-11 07:21 UTC, dragosprotung commented on tests/Unit/ReflectionClass/ReflectionClassTest.php
> +        $expected = new ReflectionDocComment("/**\r\n *\r\n * The short definition of test class 3.\r\n * This the long description of test class 3\r\n * @author test\r\n *\r\n */");
Tests are failing becuase of added `\r`

2023-05-11 08:55 UTC, javierabion commented on tests/Unit/ReflectionClass/ReflectionClassTest.php
> +        $expected = new ReflectionDocComment("/**\r\n *\r\n * The short definition of test class 3.\r\n * This the long description of test class 3\r\n * @author test\r\n *\r\n */");
Resolved in new commit

2023-05-11 08:58 UTC, javierabion reviewed
Everything solved. Thanks!

2023-05-11 09:01 UTC, dragosprotung approved these changes

2023-05-11 09:01 UTC, merged

2023-05-11 09:04 UTC, dragosprotung commented
Thank you @javierabion

2023-05-11 09:09 UTC, javierabion commented
You're wellcome! @dragosprotung